name = "gh"
description = "Generates GitHub Actions for Spin Apps"
homepage = "https://github.com/fermyon/spin-gh-plugin"
version = "0.0.4"
spin_compatibility = ">=2.0.0"
license = "Apache-2.0"
package = "gh"
